services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lolli\Dbdoctor\:
    resource: '../Classes/*'

  Lolli\Dbdoctor\Helper\PagesRootlineHelper:
    public: true
    shared: false

  Lolli\Dbdoctor\Helper\RecordsHelper:
    public: true
    shared: false

  Lolli\Dbdoctor\Helper\TableHelper:
    public: true
    shared: false

  Lolli\Dbdoctor\Renderer\AffectedPagesRenderer:
    public: true
    shared: false

  Lolli\Dbdoctor\Renderer\RecordsRenderer:
    public: true
    shared: false

  Lolli\Dbdoctor\Commands\HealthCommand:
    tags:
      - name: 'console.command'
        command: 'dbdoctor:health'
        description: 'Find and fix database inconsistencies'
